import React from "react";
import "./education.css";
import Nav from "../components/Nav";
import Footer from "../components/footer";

const education = () => {
  return (
    <>
      <header className="header1">
        <Nav />
      </header>

      <main className="maine">
        <div className="eduContainer">
          <div className="hero">
            <div className="left">
              <img
                src="https://images.pexels.com/photos/247763/pexels-photo-247763.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
                alt=""
              />
            </div>
            <div className="right">
              <h1>What are carbon footprints ?</h1>
            </div>
          </div>

          <div className="info">
            <p>
              A carbon footprint is the total amount of greenhouse gases
              (including carbon dioxide and methane) that are generated by our
              actions. The average carbon footprint for a person in the United
              States is 16 tons, one of the highest rates in the world.
              Globally, the average carbon footprint is closer to 4 tons. To
              have the best chance of avoiding a 2℃ rise in global temperatures,
              the average global carbon footprint per year needs to drop to
              under 2 tons by 2050. Lowering individual carbon footprints from
              16 tons to 2 tons doesn’t happen overnight! By making small
              changes to our actions, like eating less meat, taking fewer
              connecting flights and line drying our clothes, we can start
              making a big difference.
            </p>
          </div>
        </div>{" "}
      </main>

      <footer className="footer">
        <Footer />
      </footer>
    </>
  );
};

export default education;
